# This is the Network Flight Recorder (NFR) configuration file. Here you define
# the location of the AlphaSOC Analytics Engine, API key,, and the way in which
# NFR will monitor network traffic and score data.
# Please contact support@alphasoc.com if you have any questions.

################################################################################
# AlphaSOC Analytics Engine location and API key
################################################################################

alphasoc:

  # Location of the server
  # Default: https://api.alphasoc.net
  host: https://api.alphasoc.net

  # Your AlphaSOC API key (required to use the service)
  # Use "nfr account register" to generate one
  api_key: test-api-key

  analyze:
    # Enable (true) or disable (false) DNS event processing
    # Default: true
    dns: true
    # Enable (true) or disable (false) IP event processing
    # Default: true
    ip: true

################################################################################
# Define the network interface and protocol(s) to monitor
################################################################################

network:

  # Interface to listen for DNS events on (e.g. eth0)
  interface: <interface-name>

  # DNS network configuration
  dns:
    # Protocols to process (possible values are udp and tcp)
    # Default: [udp]
    protocols:
    - udp

    # Port to monitor for DNS traffic on
    # Default: 53
    port: 53

################################################################################
# Logging configuration
################################################################################

log:

  # File to which NFR should log
  # To print log to console use two special outputs: stderr or stdout
  # Default: stdout
  file: stdout

  # Logging level. Possibles values are: debug, info, warn, error
  # Default: info
  level: info

################################################################################
# Internal NFR data location
################################################################################

data:

  # Define the file for internal data and caching
  # Default (Linux): /run/nfr.data
  file: /run/nfr.data

################################################################################
# Monitoring scope file location (inputs)
################################################################################

scope:

   # Monitoring scope file to load
   # Default: (none)
  file:

################################################################################
# AlphaSOC alert configuration (outputs)
################################################################################

alerts:

  # Graylog server URI where AlphaSOC alerts will be sent in GELF format
  graylog:
    # URI to the server (for example tcp://127.0.0.1:12201)
    # Default: (none)
    uri:
    # Message level.
    # Default: 1
    level: 1

  # Location to which alerts should be written. This can be a file, or a special
  # ouput (stderr or stdout) to print events to the terminal
  # Default: stderr
  file: stderr

  # Interval for polling events from the Analytics Engine
  # Default: 5m
  poll_interval: 5m

################################################################################
# DNS data processing and queueing configuration
################################################################################

dns_events:

  # NFR buffer size for the DNS event queue
  # Default: 65535
  buffer_size: 65535

  # Interval for flushing data to Analytics Engine for scoring
  # Default: 30s
  flush_interval: 30s

  # If NFR is unable to send DNS events to the Analytics Engine, it can
  # write the events to disk (in PCAP format) and attempt to send them again
  failed:
    # File in which to store unprocessed DNS events on disk
    # Default: (none)
    file:

################################################################################
# IP data processing and queueing configuration
################################################################################

ip_events:

  # NFR buffer size for the IP event queue
  # Default: 65535
  buffer_size: 65535

  # Interval for flushing data to Analytics Engine for scoring
  # Default: 30s
  flush_interval: 30s

  # If NFR is unable to send IP events to the Analytics Engine, it can
  # write the events to disk (in PCAP format) and attempt to send them again
  failed:
    # File in which to store unprocessed IP events on disk
    # Default: (none)
    file:
