version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/alphasoc/nfr
    steps:
      - checkout
      - run:
          name: install libpcap-dev
          command: sudo apt-get install --quiet --yes libpcap-dev
      - run: go install ./...
      - run: go test -race ./...
      - run:
          name: build
          command: |
            GOARCH=amd64 GOOS=linux go build -o nfr-linux-amd64 -ldflags "-X github.com/alphasoc/nfr/version.Version=$(git describe)"
            GOARCH=amd64 GOOS=darwin go build -o nfr-darwin-amd6 -ldflags "-X github.com/alphasoc/nfr/version.Version=$(git describe)"
      - persist_to_workspace:
          root: .
          paths:
            - nfr-linux-amd64
            - nfr-darwin-amd64

  lint:
    docker:
      - image: mozgiii/gometalinter-docker
    working_directory: /go/src/github.com/alphasoc/nfr
    steps:
      - run:
          name: run linters
          command:  |
            gometalinter        \
            --vendor            \
            --disable-all       \
            --enable=gofmt      \
            --enable=golint     \
            --enable=goimports  \
            --enable=vetshadow  \
            --enable=misspell   \
            --enable=vet ./...

  publish:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/alphasoc/nfr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: publish
          command: |
            go get github.com/aktau/github-release
            github-release release --user alphasoc --repo nfr --tag $CIRCLE_TAG
            github-release upload --user alphasoc --repo nfr --tag $CIRCLE_TAG --name nfr-linux-amd64 --file nfr-linux-amd64
            github-release upload --user alphasoc --repo nfr --tag $CIRCLE_TAG --name nfr-darwin-amd64 --file nfr-darwin-amd64

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - lint
      - publish:
          requires:
            - build
            - lint
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
